### ISSUE TITLE
Could not find ros-humble-foxglove-compressed-video-transport via apt

### ISSUE THREAD

**Issue by atinfinity** [ros-misc-utilities/foxglove_compressed_video_transport#2]
There is the following description in README.

```bash
$ sudo apt-get install ros-${ROS_DISTRO}-foxglove-compressed-video-transport
```

But, I could not find `ros-humble-foxglove-compressed-video-transport` via apt.

```bash
$ sudo apt update
$ apt-cache search ros-humble-foxglove
ros-humble-foxglove-bridge - ROS Foxglove Bridge
ros-humble-foxglove-bridge-dbgsym - debug symbols for ros-humble-foxglove-bridge
ros-humble-foxglove-msgs - foxglove_msgs provides visualization messages that are supported by Foxglove Studio.
ros-humble-foxglove-msgs-dbgsym - debug symbols for ros-humble-foxglove-msgs
```

Do you have a plan to release this package for ROS 2 Humble?

**Comment by berndpfrommer** [comment]
It was released on September 16th, also on Humble. This may not have been synced yet (the final step that makes the packages show up in apt). There was a sync on 9/19, but I think we missed that one. Sync is usually every 4-6 weeks.

Here a link to the release repo, showing that it was released.

https://github.com/ros2-gbp/foxglove_compressed_video_transport-release
