### ISSUE TITLE
Timestamps the same

### ISSUE THREAD

**Issue by zacharyyamaoka** [ros-misc-utilities/foxglove_compressed_video_transport#3]
Hi thank you so much for putting this together!

Out of the box all the timestamps seem to be the same and the video is not playing in foxglove :(

Is this intended? Are there some params I need to set?

For the params, there doesn't seem to be the .profile, not sure if thats the problem?

.camera.color.image_rect_raw.foxglove.bit_rate
.camera.color.image_rect_raw.foxglove.delay
.camera.color.image_rect_raw.foxglove.encoding
.camera.color.image_rect_raw.foxglove.gop_size
.camera.color.image_rect_raw.foxglove.measure_performance
.camera.color.image_rect_raw.foxglove.performance_interval
.camera.color.image_rect_raw.foxglove.pixel_format
.camera.color.image_rect_raw.foxglove.preset
.camera.color.image_rect_raw.foxglove.qmax
.camera.color.image_rect_raw.foxglove.tune

Best,

Zach

![image](https://github.com/user-attachments/assets/27ab0965-cd02-4a19-829d-f29336285cfa)

**Comment by berndpfrommer** [comment]
Packages with the bug fix have been released. It typically takes a few months until they work their way through the system. Closing this issue for now.
